baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'archie'


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Research Groups"
url = "/research"
weight = 2

[[menu.main]]
name = "Events"
url = "/events"
weight = 3

[[menu.main]]
name = "Talks"
url = "/talks"
weight = 4

[[menu.main]]
name = "Tools"
url = "/tools"
weight = 5