baseURL = 'https://mlsysops.github.io/ai-engineering/'
languageCode = 'en-us'
title = 'Awesome AI Engineering'
theme = 'archie'


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Research Groups"
url = "/research"
weight = 2

[[menu.main]]
name = "Events"
url = "/events"
weight = 3

[[menu.main]]
name = "Course"
url = "/course"
weight = 4

[[menu.main]]
name = "Company"
url = "/company"
weight = 5

[[menu.main]]
name = "Tools"
url = "/tools"
weight = 6